### ISSUE TITLE
NPE causes retry loop of task queue

### ISSUE THREAD

**Issue by int128** [int128/gradleupdate#8]
```
    I 12:22:30.599 com.google.apphosting.runtime.security.shared.intercept.java.lang.reflect.Method_$1 run: Created build.gradle as 259c008d2856835fd6b5a68ca90c568de3f7304c on repository gradleupdate/gradle-plugin-blank
    I 12:22:30.599 com.google.apphosting.runtime.security.shared.intercept.java.lang.reflect.Method_$1 run: Creating a branch gradle-2.9 from master on repository gradleupdate/gradle-plugin-blank
    W 12:22:31.289 /internal/pull-request-for-gradle/4-branch.groovy
      java.lang.NullPointerException: Cannot get property 'sha' on null object
      	at gradle.Repository.createBranch(Repository.groovy:123)
      	at 4-branch.run(4-branch.groovy:24)
    F 12:22:31.290 Uncaught exception from servlet
      java.lang.NullPointerException: Cannot get property 'sha' on null object
      	at gradle.Repository.createBranch(Repository.groovy:123)
      	at 4-branch.run(4-branch.groovy:24)
```

https://github.com/int128/gradleupdate/blob/c14e3fa2f88bda33a2409e17677300af2a739f6a/src/main/groovy/gradle/Repository.groovy#L123

```groovy
        def newRef = gitHub.createReference(fullName, branch, newCommit.sha)
        assert newRef.object.sha instanceof String
```

**Comment by int128** [comment]
https://developer.github.com/v3/git/refs/#create-a-reference

**Comment by int128** [comment]
1. Add null checking for the result of create reference.
1. Fix assertion with `.?`
